### ISSUE TITLE
User Experience: Building a high fidelity prototype of an app using Figma & JIRA

### ISSUE THREAD

**Issue by yumnarefai** [learning-software-engineering/learning-software-engineering.github.io#413]
The current document doesn't necessarily demonstrate how to build the user flow and create a set of pages for an application using Figma. 

Thus, with the use of task management tools like JIRA, I intend to help developers utilize the core essentials of Figma to develop a high fidelity prototype for an app. This adds value to the overall software experience for developers working at startups or running their own company because it ensure efficient project delivery from design to development.

**Comment by savannapan** [comment]
I will be working on this with Yumna as well.

**Comment by Arick-mux** [comment]
Hi I have experience in this topic from previous courses as well as from previous jobs. Would you like another partner?

**Comment by helias22** [comment]
I will be working on this with Yumna and Savanna as well.

**Comment by yumnarefai** [comment]
> Hi I have experience in this topic from previous courses as well as from previous jobs. Would you like another partner?

Hey @Arick-mux, thank you for reaching out! Unfortunately, we're currently full :(

Good luck with A2. :)
