### ISSUE TITLE
Automate Tasks with Python using PyAutoGUI

### ISSUE THREAD

**Issue by manav393** [learning-software-engineering/learning-software-engineering.github.io#434]
PyAutoGUI is a Python module that allows users to control the mouse and keyboard to automate tasks programmatically. We aim to provide a comprehensive guide on using PyAutoGUI for automation using Python.

Team Members:
Manav Manoj Malviya - malviya4
Mann Thakkar - thakka86

**Comment by manndthakkar** [comment]
Worked on this issue with Manav. Here is my pull request:

https://github.com/learning-software-engineering/learning-software-engineering.github.io/pull/558
