### ISSUE TITLE
A Guide on using Tiptap in a React CRUD app. 

### ISSUE THREAD

**Issue by AshkanAleshams** [learning-software-engineering/learning-software-engineering.github.io#443]
Create the Guide on  using Tiptap in a React CRUD app. 
We will introduce Tiptap via by a step-by-step demo of the Tiptap Markdown Extension as an example.

**Comment by AshkanAleshams** [comment]
@AshkanAleshams @htysc

**Comment by htysc** [comment]
Resolved by #575
