### ISSUE TITLE
Tech Stack: Memory Safety in Rust

### ISSUE THREAD

**Issue by minjaedavidpark** [learning-software-engineering/learning-software-engineering.github.io#460]
Cybersecurity & Infrastructure Security Agency (CISA) released an article about memory safety, urging the use of memory-safe languages such as Rust over the unsafe languages like C or C++ to developers. 
We will talk about how memory safety is done in Rust and compare and contrast between Rust and the aforementioned memory-unsafe languages.
Since most of us in CSC301 would have no experience with Rust, we will include a brief introduction to Rust to encourage the use and learning of the language among us.

The link of the article can be found: https://www.cisa.gov/news-events/news/urgent-need-memory-safety-software-products

**Comment by jaffarkeikei** [comment]
That is amazing David! I totally agree with you that we need more safety in memory management, especially with very low level languages.

**Comment by Affixrevy** [comment]
David has a great idea! Memory management is critical and definitely something we as programmers should take into account. Knowing a memory safe language like Rust will definitely help with that.
