### ISSUE TITLE
Tech Stack : Introduction to p5.js

### ISSUE THREAD

**Issue by kimmy190** [learning-software-engineering/learning-software-engineering.github.io#494]
Introduction to the JS 3d library three.js, its setup and dive into its basic components.

**Comment by nat0cat** [comment]
I will be working on this topic as well.

**Comment by sinemsoylemezoglu** [comment]
I will be working on this topic as well.

**Comment by kimmy190** [comment]
Considering that this topic was already taken, we will discuss the introduction to the JS creative coding library p5.js, its setup and dive into its basic components.

**Comment by kimmy190** [comment]
All the required content has been covered by team members.
