### ISSUE TITLE
Product Management: Agile Product Development Methodologies & User-Centered Design (UCD) Vs. Design-Driven Development (DDD)

### ISSUE THREAD

**Issue by darpanmishra** [learning-software-engineering/learning-software-engineering.github.io#530]
In today's rapidly evolving tech landscape, where adaptability and efficiency are paramount, embracing modern software development methodologies is essential. Agile product development strategies and user-centric design principles have emerged as fundamental approaches to meet the dynamic demands of the industry.

Many of our CSC301 partners are on the lookout for innovative solutions that prioritize user needs and deliver exceptional user experiences. This is where Agile methodologies and user-centered design play pivotal roles in shaping the development process. Agile practices foster collaboration, iteration, and continuous improvement, enabling teams to respond swiftly to changing requirements and deliver value incrementally. On the other hand, user-centered design ensures that products are intuitive, accessible, and aligned with user expectations, ultimately leading to enhanced customer satisfaction and product success.

I propose to add the following to the repo:

- A new subheading page in Product Management under Core Concepts in Product Management titled:

 > Introduction to Agile Product Development Methodologies

This page will also have links to the more in depth and descriptive pages on the methodologies such as Lean. The page itself will be more centered around its correlation to being a core concept of Product Management. 

- Another subheading page titled 

> User-Centered Design (UCD) Vs. Design-Driven Development (DDD)

Subheadings will include the following:

### Subheadings

1. **Understanding User-Centered Design (UCD)**
   - Introduction to UCD
   - Discussion of principles of UCD and sits role in product management and develoipment. 

2. **Understanding Design-Driven Development (DDD)**
   - Intro to DDD and its methodology.
   - Explanation of how DDD integrates design thinking to be crucial and its effects on different products. 

3. **Key Differences between UCD and DDD**
   - Overview of similarities and differences
   - Why one may be used over the other and the decisions that a Product Manger would make towards it.
   - Topics: usability vs. innovation; approach to problem solving and final product needs; combining UCD and DDD

4. **Understanding Agile Methodologies**
   - Basic overview of Agile

5. **Lean, Kanban, MVC, Scrum**
   - Overviews and examples in regards to product manager scenarios. Links to more detailed versions of the topcis as they are found in the Software Engineering section of the repo. 
   
6. **Agile Product Planning and Prioritization**
   - User story mapping
   - Roadmapping

**Comment by aryangoel24** [comment]
Adding a subheading titled Introduction to Agile Product Development Methodologies, and supplementing it with the section User-Centered Design (UCD) Vs. Design-Driven Development (DDD) is a fantastic idea. These are the primary ideas that drive a products development even before any of the actual development begins. Therefore understanding the differences between these concepts is critical for a successfully engineered product. If the students in 301 were to learn these practices prior to starting, it would definitely aid in their decision making and give them a clearer idea of what they want to work on.
