### ISSUE TITLE
Postman Environment Variables Setting and Mock Server

### ISSUE THREAD

**Issue by Eileen1003** [learning-software-engineering/learning-software-engineering.github.io#602]
Postman_backend_testing offers basic instructions on testing API endpoints using Postman. However, utilizing Postman's environment variable settings can be beneficial when you require varying values in requests based on context. Additionally, the Mock server feature proves helpful for developing or testing an API before it's production-ready, or when production data isn't available. Providing instructions for these features can deepen readers' understanding of Postman's comprehensive functionality.

**Comment by Damngoblin** [comment]
Adding this content can indeed help developers better understand the functionality of Postman. The Mock Server can accelerate front-end and back-end parallel development during the project development process, thus it benefits CSC301 students. The Environment feature can enhance the flexibility of API testing, saving time and reducing errors in practical work!
